spring.application.name=productos-api

# Configuración de la Base de Datos H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola H2 en /h2-console
spring.h2.console.enabled=true
# Para que la consola H2 funcione con Spring Security
spring.h2.console.path=/h2-console

# Configuración de JPA (Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Para que cree/actualice las tablas solas
spring.jpa.hibernate.ddl-auto=update

# Para ver qué hace JPA por atrás
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de SpringDoc (Swagger)
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/api-docs
